POST http://localhost:5000/projects
Content-Type: application/json

{
    "projectName": "Ordering App Upnormal",
    "projectType": "Mobile",
    "dealPrice": 32000000,
    "worker": 4,
    "duration": 3
}