GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJSeWhtYW4gQWppIFBhbmdpc3R1IiwiZW1haWwiOiJyeTAwaG1hbkBleGFtcGxlLmNvbSIsInVzZXJuYW1lIjoicnkwMGhtYW4iLCJyb2xlIjoiYWRtaW4iLCJhZGRyZXNzIjoiR2FydXQiLCJpYXQiOjE2Njc0MTk3MzcsImV4cCI6MTY2NzQxOTc5N30.QXr-0EkODSd3F7PlZFBmTe3lyWfj9wbx1BoFa6IvEBI

###
POST http://localhost:5000/register
Content-Type: application/json

{
    "name": "Ryhman Aji Pangistu",
    "email": "ry00hman@example.com",
    "username": "ry00hman",
    "password": "secret",
    "confPassword": "secret",
    "role": "admin",
    "address": "Garut"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "username": "ry00hman",
    "password": "secret"
}

###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout