POST http://localhost:5000/login
Content-Type: application/json

{
    "username": "ry00hman",
    "password": "secret"
}

###
POST http://localhost:5000/token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJSeWhtYW4iLCJlbWFpbCI6InJ5MDBobWFuQGV4YW1wbGUuY29tIiwidXNlcm5hbWUiOiJyeTAwaG1hbiIsInJvbGUiOiJBZG1pbiIsImFkZHJlc3MiOiJCYW5kdW5nIiwiaWF0IjoxNjY4MjY2ODIyLCJleHAiOjE2NjgyNzQwMjJ9.iIaIRgwJN2jagY6UdhwCstH5AlfMp9yG-FUMfW84AII"
}

###
GET http://localhost:5000/project-status
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJSeWhtYW4iLCJlbWFpbCI6InJ5MDBobWFuQGV4YW1wbGUuY29tIiwidXNlcm5hbWUiOiJyeTAwaG1hbiIsInJvbGUiOiJBZG1pbiIsImFkZHJlc3MiOiJCYW5kdW5nIiwiaWF0IjoxNjY4MjY2ODMzLCJleHAiOjE2NjgyNjc0MzN9.-t_cgsm7YOnAmMir_MOaDHh2aBneSzXsWqRvcN4wzF0
Content-Type: application/json

{
    "status": "Not Started"
}